### ISSUE TITLE
tauri + puppeteer + pkg

### ISSUE THREAD

**Issue by 93null** [93null/fubar#5]

**Comment by 93null** [comment]
This is the stack I'd like to get to work.
# Tauri/Puppeteer/Pkg vs Electron/BrowserWindow
Puppeteer can close the headless browser when not needed. Electron can't stop running chromium.
Electron would be easier to setup, but Puppeteer enables better automation and evasion.
# Tasks
- [ ] Implement Tauri Sidecar pattern to communicate with nodejs app from GUI
- [ ] install puppeteer and call browsing function from GUI
- [ ] [build](https://github.com/vercel/pkg/issues/204) for windows
- [ ] build for linux

**Comment by 93null** [comment]
# Implement Tauri Sidecar pattern to communicate with nodejs app from GUI

Example code: https://github.com/tauri-apps/tauri/blob/dev/examples/sidecar

- [ ] update tauri.conf.json
* runs package command
* sets binaries directory
* sets sidecar pattern
```
{
  "build": {
    "distDir": ["../index.html"],
    "devPath": ["../index.html"],
    "beforeDevCommand": "yarn package",
    "beforeBuildCommand": "yarn package",
    "withGlobalTauri": true
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "../../.icons/32x32.png",
        "../../.icons/128x128.png",
        "../../.icons/128x128@2x.png",
        "../../.icons/icon.icns",
        "../../.icons/icon.ico"
      ],
      "resources": [],
      "externalBin": ["binaries/app"],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": []
      },
      "macOS": {
        "frameworks": [],
        "exceptionDomain": ""
      }
    },
    "allowlist": {
      "all": false,
      "shell": {
        "sidecar": true,
        "scope": [
          {
            "name": "binaries/app",
            "sidecar": true
          }
        ]
      }
    },
    "windows": [
      {
        "title": "Sidecar",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": "default-src 'self'"
    },
    "updater": {
      "active": false
    }
  }
}
```
- [ ] update package.json
* defines node app entry (bin)
* defines pkg assets
* defines package/pkg script to create and move binaries
* defines tauri/tooling script
```
{
  "name": "sidecar",
  "version": "1.0.0",
  "bin": "src/index.js",
  "pkg": {
    "assets": [
      "src/**/*"
    ]
  },
  "scripts": {
    "tauri": "node ../../tooling/cli/node/tauri.js",
    "package": "pkg package.json --output src-tauri/binaries/app && node scripts/move-binary.js"
  },
  "devDependencies": {
    "execa": "5.1.1",
    "pkg": "5.2.1"
  }
}
```
- [ ] create scripts/move-binary.js
```
/**
 * This script is used to rename the binary with the platform specific postfix.
 * When `tauri build` is ran, it looks for the binary name appended with the platform specific postfix.
 */

const execa = require('execa')
const fs = require('fs')

let extension = ''
if (process.platform === 'win32') {
  extension = '.exe'
}

async function main() {
  const rustInfo = (await execa('rustc', ['-vV'])).stdout
  const targetTriple = /host: (\S+)/g.exec(rustInfo)[1]
  if (!targetTriple) {
    console.error('Failed to determine platform target triple')
  }
  fs.renameSync(
    `src-tauri/binaries/app${extension}`,
    `src-tauri/binaries/app-${targetTriple}${extension}`
  )
}

main().catch((e) => {
  throw e
})
```
- [ ] make tauri.js
* names binary?
make sure to update path in package.json
```
#!/usr/bin/env node

const cli = require('./main')
const path = require('path')

const [bin, script, ...arguments] = process.argv
const binStem = path.parse(bin).name.toLowerCase()

// We want to make a helpful binary name for the underlying CLI helper, if we
// can successfully detect what command likely started the execution.
let binName

// Even if started by a package manager, the binary will be NodeJS.
// Some distribution still use "nodejs" as the binary name.
if (binStem === 'node' || binStem === 'nodejs') {
  const managerStem = process.env.npm_execpath
    ? path.parse(process.env.npm_execpath).name.toLowerCase()
    : null
  if (managerStem) {
    let manager
    switch (managerStem) {
      // Only supported package manager that has a different filename is npm.
      case 'npm-cli':
        manager = 'npm'
        break

      // Yarn and pnpm have the same stem name as their bin.
      // We assume all unknown package managers do as well.
      default:
        manager = managerStem
        break
    }

    binName = `${manager} run ${process.env.npm_lifecycle_event}`
  } else {
    // Assume running NodeJS if we didn't detect a manager from the env.
    // We normalize the path to prevent the script's absolute path being used.
    const scriptNormal = path.normalize(path.relative(process.cwd(), script))
    binName = `${binStem} ${scriptNormal}`
  }
} else {
  // We don't know what started it, assume it's already stripped.
  arguments.unshift(bin)
}

cli.run(arguments, binName).catch((err) => {
  console.log(`Error running CLI: ${err.message}`)
  process.exit(1)
})
```
- [ ] spawn command in main.rs
````
// Copyright 2019-2021 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

use tauri::{
  api::process::{Command, CommandEvent},
  Manager,
};

fn main() {
  tauri::Builder::default()
    .setup(|app| {
      let window = app.get_window("main").unwrap();
      tauri::async_runtime::spawn(async move {
        let (mut rx, mut child) = Command::new_sidecar("app")
          .expect("failed to setup `app` sidecar")
          .spawn()
          .expect("Failed to spawn packaged node");

        let mut i = 0;
        while let Some(event) = rx.recv().await {
          if let CommandEvent::Stdout(line) = event {
            window
              .emit("message", Some(format!("'{}'", line)))
              .expect("failed to emit event");
            i += 1;
            if i == 4 {
              child.write("message from Rust\n".as_bytes()).unwrap();
              i = 0;
            }
          }
        }
      });

      Ok(())
    })
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
````
- [ ] communicate with node app in front end via stdout
````
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sidecar</title>
  <style>
    .container {
      display: flex;
    }
    .container > div {
      flex: 1;
    }
  </style>
</head>

<body>
  <div class="container">
    <div id="backend"></div>
    <div id="frontend"></div>
  </div>
  <script>
    function addMessage(div, message) {
      const p = document.createElement('p')
      p.innerText = message
      div.appendChild(p)
    }

    const backendDiv = document.getElementById('backend')
    window.__TAURI__.event.listen('message', (event) => {
      addMessage(backendDiv, event.payload)
    })

    const frontendDiv = document.getElementById('frontend')
    const { Command } = window.__TAURI__.shell
    const command = Command.sidecar('binaries/app')
    command.on('close', data => {
      addMessage(frontendDiv, `command finished with code ${data.code} and signal ${data.signal}`)
    })
    command.on('error', error => addMessage(frontendDiv, `command error: "${error}"`))
    command.stdout.on('data', line => addMessage(frontendDiv, `command stdout: "${line}"`))
    command.stderr.on('data', line => addMessage(frontendDiv, `command stderr: "${line}"`))
    command.spawn()
  </script>
</body>

</html>
````
- [ ] create node app at index.js and communication.js
````
const { write, onMessage } = require('./communication')

onMessage((line) => {
  write(`read ${line}`)
})

setInterval(() => {
  write(`[${new Date().toLocaleTimeString()}] new message`)
}, 500)
````
````
const readline = require('readline')

module.exports = {
  onMessage(cb) {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: false
    })

    rl.on('line', function (line) {
      cb(line)
    })
  },
  write(message) {
    console.log(message)
  }
}
````

**Comment by 93null** [comment]
# install puppeteer and call browsing function from GUI

- [ ] copy .local-chromium to src-tauri/binaries & src-tauri/target/debug

- [ ] launch browser relative to executable location
`substring(4)` because resulting path for me has 4 extra characters. it's 4am. i'll figure it out later. edited after pasting, may have errors.
````js
const browser = await puppeteer.launch({
      executablePath: puppeteer.executablePath().replace(
    /^.*?\\node_modules\\puppeteer\\\.local-chromium/,      //<------ That is for windows users, for linux users use:  /^.*?\/node_modules\/puppeteer\/\.local-chromium/ 
    path.join(path.dirname(process.execPath), '.local-chromium')   //<------ Folder name, use whatever you want
  ).substring(4),
...});
````
credit: https://github.com/vercel/pkg/issues/204#issuecomment-948042849

**Comment by 93null** [comment]
# build for windows

- [ ] implement youtube search feature
* submit query
* browse to page with puppeteer
* return and display list of results
- [ ] build and run using manually copied `.local-chromium`
- [ ] copy chromium during build/install

**Comment by 93null** [comment]
Using puppeteer-core and bundling chromium with Tauri somehow probably would have been the way to continue from here.
# On bundling Node
Packaging Node runtime to run puppeteer + Chromium, unless I'm doing something wrong (likely), means 400mb+ before the app is even useful. Including the node runtime could make a lot of things easier now and in the future, but it's heavy and adds more complexity than I wish to deal with.
Rust is already accessible in the 4mb default tauri executable/installer. A better solution will involve using rust to control a headless browser or webdriver client, instead of importing the entire nodejs runtime to use one (awesome) package to control it.
https://github.com/93null/fubar/issues/7
