### ISSUE TITLE
v0.1.0 roadmap & tasks

### ISSUE THREAD

**Issue by 93null** [93null/fubar#9]

**Comment by 93null** [comment]
# v0.1.0 Features Overview
## React Components
Search bar
* Lint queries locally on input
* Send queries to managers

Request Manager
* Route requests between frontend and backend

Download Manager
* download data as requested and send to file manager
* show progress

File Manager
* recieve data from download manager and save to appropriate repository
* manage local repositories

Bot Manager
* manage bots

Plugin Manager
* manage plugins

Tabs
* create views upon recieving data
* manage views

Result View
* Display recieved data
* Send requests

App view
* display app gui
* send requests
* accept data

# Apps
Media player
Text viewer

# Plugins
Search plugins
Result plugins
App plugins

# Rust Backend
Make requests
Process data

**Comment by 93null** [comment]
#v0.1.0 Roadmap

## Setup

- [ ] Remove all webdriver code
- [ ] Interface between frontend and backend with request manager background component
- [ ] Implement react router
- [ ] Create tabs route (/{tab})
- [ ] Create manager singleton routes
- [ ] Connect components as necessary

## Plugins (search/results/save/view/index)

- [ ] Youtube
  - [ ] Video
  - [ ] Audio
  - [ ] Playlists
- [ ] Github
  - [ ] Markdown
  - [ ] Software
  - [ ] Link lists
- [ ] Stack Overflow
  - [ ] Questions
  - [ ] Answers
- [ ] Archive.org
  - [ ] Audio
  - [ ] Images/Video
  - [ ] Text
  - [ ] Software
- [ ] Reddit
  - [ ] Threads
  - [ ] Comments
  - [ ] Links
  - [ ] Images/Video
- [ ] Project Gutenberg
  - [ ] Books
- [ ] Programming language documentation

**Comment by 93null** [comment]
https://github.com/93null/fubar/issues/10
